version: '3.3'

services:
  
  db:
    image: postgres:14.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  rabbitmq:
      restart: always
      image: 'bitnami/rabbitmq:3.8'
      ports:
        - '4369:4369'
        - '5672:5672'
        - '25672:25672'
        - '15672:15672'

  auth-service:
    image: trypanosomadev/auth-service:local
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRE_USER: postgres
      POSTGRE_PASSWORD: password
      POSTGRE_IP: db
      POSTGRE_PORT: 5432
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: user
      RABBIT_PASSWORD: bitnami
      SERVER_PORT: 8080
      DB_NAME: registration
    

  book-service: 
    image: trypanosomadev/book-service:local
    restart: always
    ports:
      - 8081:8081
    environment:
      POSTGRE_USER: postgres
      POSTGRE_PASSWORD: password
      POSTGRE_IP: db
      POSTGRE_PORT: 5432
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: user
      RABBIT_PASSWORD: bitnami
      SERVER_PORT: 8081
      DB_NAME: book_service
      AUTH_SERVICE_URL: http://auth-service:8080/api/v1/authentication?role=%s
